os: linux
language: shell

services:
- docker

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    secure: ElqxMj9A1qDWfCWL8PGvSqd0i5fG3ltS+GV1B3trY9JKiqYxaWYIYMS9WDme5M9lnRoDnRI7APOqFW/1Aow5A+v9sQuZksV19GER/vO4qICOYAHmvQmcwpZc8wub38MXdtyLcPIcdqZxYp28mZ0z2HgRL2nAvN2BaGExLWynLvkTwE5unSnkX1Yw34n0E2Jp+oVtk/r8CnWqe9iy5XhXFdXfRSYzVAXPFk8hlJOHUZyVDC1gLpxlju0QHD4r4J0xZ8M0utYkR+2HkSaCxtiEi8E/IeZUFblfjbaphbUghxx9fMvgiLlUDC1iP0F6AlY1wguyy3H6RHDLddaR4OB6EwC4Qr3D7Tow2dhcc4hKcs3WtaeKLn2N3V4eTElsyV7G9L2Vv6DDq4rIMunpuhmNJC3v5QUHrjT7jfZSuS2Eti+zkkWokB+1j01G76C/3h/k0ZSJjus/pxPV6BTV3xUeBn3+47Q/R3Uim10WckIh84bJEscnshC9Tmc/JPooWGjlasgWZllnPw0j4xk7d5vM6KKYkHDZ/4wWu/XtzG8g7FevGFn3KeAiBKmK2oKVDIhMwG+R/AXvOYWWM0GMPL92BiwA+VsFGQn7dqetvLCCM5+c9CSkwbru7fo3C/KTbCrTsSC6Oe4o9ARuiUeFH+cyPpLqT1q8GYYV+81mN8gqVRY=

  matrix:
  - ARCH=amd64 GOARCH=amd64 GOARM=6 QQEMU_ARCH=x86_64 TAG=amd64
  - ARCH=armhf GOARCH=arm   GOARM=6 QEMU_ARCH=arm     TAG=arm
  - ARCH=arm64 GOARCH=arm64 GOARM=6 QEMU_ARCH=arm64   TAG=arm64

before_install:
- mkdir ~/.docker && echo '{ "experimental":"enabled" }' > ~/.docker/config.json
- curl -L https://goss.rocks/install | sudo sh
- sudo apt-get -y install qemu-user-static
- docker run --rm --privileged multiarch/qemu-user-static:register

stages:
  - name: test
  - name: push

script:
  - docker build -t $repo:$TAG --build-arg ARCH="$ARCH" --build-arg GOARCH="$GOARCH" --build-arg GOARM="$GOARM" ./
  - dgoss run --name cloudflared -ti $repo:$TAG
  - echo "$DOCKER_PASSWORD" | docker login -u=$username --password-stdin
  - docker push $repo:$TAG

jobs:
  include:
     - stage: push
       script:
       - echo "$DOCKER_PASSWORD" | docker login -u=$username --password-stdin
       - docker pull $repo:arm
       - docker pull $repo:arm64
       - docker pull $repo:amd64
       - docker manifest create --amend $repo:latest $username/$repo:arm $repo:arm64 $repo:amd64
       - docker manifest annotate $repo:latest $repo:arm --os linux --arch arm
       - docker manifest annotate $repo:latest $repo:arm64 --os linux --arch arm64
       - docker manifest annotate $repo:latest $repo:amd64 --os linux --arch amd64
       - docker manifest push --purge $repo:latest
